platform :ios, '13.0'

target 'iOS-AllFuncs' do
  use_frameworks!

  # Pods for iOS-AllFuncs
  
    pod 'CLTypingLabel', '~> 0.4.0'
    pod 'FirebaseAuth'
    pod 'FirebaseFirestore'
    pod 'IQKeyboardManagerSwift'
    pod 'RealmSwift'
end
